### ISSUE TITLE
Django 3.1

### ISSUE THREAD

**Issue by ajslater** [contmp/django-dark#1]
Looks like there've been some changes in Django 3.1. The Django 3.1 beta has many elements that need `background-color: inherit` and a few input controls that need that dark styling as well.

Text color probably needs fixing on many admin screens as well, but I didn't investigate fully.

**Comment by contmp** [comment]
I see, thank you for the hint and suggestions!
Just checked out django 3.1b1 but it still looks too unfinished to me to already adapt styles to it. If 3.1 reached rc state, I will try to adjust dark asap. Feel free to contribute too.

**Comment by ajslater** [comment]
3.1rc1 is scheduled for July 21. I'll see if I can free up some time to contribute.

**Comment by dtcooper** [comment]
Heya! Just curious about this. Definitely not displaying well on Django 3.1.

Thanks!

**Comment by contmp** [comment]
Thanks for the reminder! I will update the styles and package during this week
