### ISSUE TITLE
Is this only for django admin pages?

### ISSUE THREAD

**Issue by 9mido** [contmp/django-dark#2]
Wondering if this is only for admin pages.

If it is only for admin, it would be nice to expand this to be for other static css pages in your apps.

**Comment by contmp** [comment]
Yes, it is only meant to override django admin specific styles, elements and classes.
On the other hand I guess implementing dark mode for other apps should be custom or framework based or what did you meant by other static css pages?

**Comment by 9mido** [comment]
I see. Although definitely useful for admin specific sites, it would have been nice to use it on the rest of your project as well. Yes that is what I meant. So something like that is not doable since it is more custom and different for each site?

**Comment by contmp** [comment]
As long as you are talking about a scope within the django admin it would be possible and welcomed to support 3rd party as long as it's widely used, good practise or simply just worth it. You can name a package you wish to support and I will try to take a look or of course you can provide a merge request if you wish to contribute to this light project.
